import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title> Home One || SureChoice </title>

    <link rel="apple-touch-icon" sizes="180x180" href="img/apple-touch-icon.png"/>
    <link rel="icon" type="image/png" sizes="32x32" href="img/favicon-32x32.png"/>
    <link rel="icon" type="image/png" sizes="16x16" href="img/favicon-16x16.png"/>
    <link rel="manifest" href="assets/images/favicons/site.webmanifest"/>

    <link rel="preconnect" href="https://fonts.googleapis.com"/>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin=""/>
    <link href="css/css2.css" rel="stylesheet"/>

    <link rel="stylesheet" href="/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="/css/animate.min.css"/>
    <link rel="stylesheet" href="/css/custom-animate.css"/>
    <link rel="stylesheet" href="/css/all.min.css"/>
    <link rel="stylesheet" href="/css/jarallax.css"/>
    <link rel="stylesheet" href="/css/jquery.magnific-popup.css"/>
    <link rel="stylesheet" href="/css/nouislider.min.css"/>
    <link rel="stylesheet" href="/css/nouislider.pips.css"/>
    <link rel="stylesheet" href="/css/odometer.min.css"/>
    <link rel="stylesheet" href="/css/swiper.min.css"/>
    <link rel="stylesheet" href="/css/style.css"/>
    <link rel="stylesheet" href="/css/style_1.css"/>
    <link rel="stylesheet" href="/css/tiny-slider.min.css"/>
    <link rel="stylesheet" href="/css/stylesheet.css"/>
    <link rel="stylesheet" href="/css/owl.carousel.min.css"/>
    <link rel="stylesheet" href="/css/owl.theme.default.min.css"/>
    <link rel="stylesheet" href="/css/jquery.bxslider.css"/>
    <link rel="stylesheet" href="/css/bootstrap-select.min.css"/>
    <link rel="stylesheet" href="/css/vegas.min.css"/>
    <link rel="stylesheet" href="/css/jquery-ui.css"/>
    <link rel="stylesheet" href="/css/timePicker.css"/>
    <link rel="stylesheet" href="/css/ion.rangeSlider.min.css"/>
    <link rel="stylesheet" href="/css/vegas.min.css"/>
    <link rel="stylesheet" id="langLtr" href="/css/insur.css"/>
</head>
      <body  className="custom-cursor">
      {/* <noscript>You need to enable JavaScript to run this app.</noscript> */}

        <div className="page-wrapper">
        {children}
        <div class="search-popup">
        <div class="search-popup__overlay search-toggler"></div>

        <div class="search-popup__content">
            <form action="#">
                <label for="search" class="sr-only">search here</label>
                <input type="text" id="search" placeholder="Search Here..."/>
                <button type="submit" aria-label="search submit" class="thm-btn">
                    <i class="icon-magnifying-glass"></i>
                </button>
            </form>
        </div>

    </div>
        </div>

    <a href="#" data-target="html" class="scroll-to-target scroll-to-top"><i class="fa fa-angle-up"></i></a>
    
    <Script src="/js/bootstrap.bundle.min.js"></Script>
    <Script src="/js/jarallax.min.js"></Script>
    <Script src="/js/jquery.ajaxchimp.min.js"></Script>
    <Script src="/js/jquery.appear.min.js"></Script>
    <Script src="/js/jquery.circle-progress.min.js"></Script>
    <Script src="/js/jquery.magnific-popup.min.js"></Script>
    <Script src="/js/jquery.validate.min.js"></Script>
    <Script src="/js/nouislider.min.js"></Script>
    <Script src="/js/odometer.min.js"></Script>
    <Script src="/js/swiper.min.js"></Script>
    <Script src="/js/tiny-slider.min.js"></Script>
    <Script src="/js/wNumb.min.js"></Script>
    <Script src="/js/wow.js"></Script>
    <Script src="/js/isotope.js"></Script>
    <Script src="/js/countdown.min.js"></Script>
    <Script src="/js/owl.carousel.min.js"></Script>
    <Script src="/js/jquery.bxslider.min.js"></Script>
    <Script src="/js/bootstrap-select.min.js"></Script>
    <Script src="/js/vegas.min.js"></Script>
    <Script src="/js/jquery-ui.js"></Script>
    <Script src="/js/timePicker.js"></Script>
    <Script src="/js/jquery.circleType.js"></Script>
    <Script src="/js/jquery.lettering.min.js"></Script>
    <Script src="/js/ion.rangeSlider.min.js"></Script>

    <Script src="/js/insur.js"></Script>
      <Script src="/js/jquery-3.6.0.min.js"></Script>
      </body>
    </html>
  );
}
